# -*- coding: utf-8 -*-
"""github.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZiNG0K7VlIMpYg8hIHwE2K4kr-LYbTwt
"""



print("=== Sum of Two Numbers ===")

# Get input from the user
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

# Calculate the sum
sum_result = num1 + num2

# Display the result
print("\nThe sum of", num1, "and", num2, "is:", sum_result)